"""Remove brand_slug from Car

Revision ID: 01e7829c7bd4
Revises: 1cc08a121832
Create Date: 2025-04-10 21:31:45.967143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e7829c7bd4'
down_revision: Union[str, None] = '1cc08a121832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'brand_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('brand_slug', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
