"""add brand modifications table

Revision ID: 336ade5d969f
Revises: 15ef925c4c6e
Create Date: 2025-04-28 16:58:53.783119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336ade5d969f'
down_revision = '15ef925c4c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'brand_id', name='unique_modification_per_brand')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_modifications')
    # ### end Alembic commands ###
