"""Add Country model and foreign key to Brand

Revision ID: 4f1ef3d17dc9
Revises: bc882a5ced8f
Create Date: 2025-04-10 17:41:15.283176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1ef3d17dc9'
down_revision: Union[str, None] = 'bc882a5ced8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table('brands', schema=None) as batch_op:

        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              autoincrement=True)

        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=50),
                              existing_nullable=False)

        batch_op.alter_column('slug',
                              existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=50),
                              existing_nullable=False)

        batch_op.create_unique_constraint('uq_brand_name', ['name'])
        batch_op.create_unique_constraint('uq_brand_slug', ['slug'])

        batch_op.drop_column('category')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              autoincrement=True)

        batch_op.create_unique_constraint('uq_country_name', ['name'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')

    op.add_column('brands', sa.Column('category', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'brands', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')

    op.drop_column('brands', 'created_at')
    # ### end Alembic commands ###
