"""Add Country model and foreign key to Brand

Revision ID: 4f1ef3d17dc9
Revises: bc882a5ced8f
Create Date: 2025-04-10 17:41:15.283176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1ef3d17dc9'
down_revision: Union[str, None] = 'bc882a5ced8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('created_at', sa.DateTime(), nullable=True))

    op.create_unique_constraint(None, 'brands', ['name'])
    op.create_unique_constraint(None, 'brands', ['slug'])
    op.drop_column('brands', 'category')

    op.create_unique_constraint(None, 'countries', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')

    op.add_column('brands', sa.Column('category', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'brands', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')

    op.drop_column('brands', 'created_at')
    # ### end Alembic commands ###
