"""Add brand_logo field

Revision ID: a5e6eec51a86
Revises: 
Create Date: 2025-04-09 15:08:58.720566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e6eec51a86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('category')
    op.add_column('cars', sa.Column('brand_logo', sa.String(length=200), nullable=True))
    op.add_column('categories', sa.Column('icon', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    op.drop_column('cars', 'brand_logo')
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('car',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.VARCHAR(length=20), nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('specs', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('in_stock', sa.BOOLEAN(), nullable=True),
    sa.Column('is_electric', sa.BOOLEAN(), nullable=True),
    sa.Column('is_hybrid', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
