"""Add Brand and CarType models

Revision ID: d5729cd0fc25
Revises: 54a43d817025
Create Date: 2025-04-09 20:29:34.383385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5729cd0fc25'
down_revision: Union[str, None] = '54a43d817025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('brand_slug', sa.String(length=50), nullable=True))
    op.add_column('cars', sa.Column('car_type_slug', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'car_type_slug')
    op.drop_column('cars', 'brand_slug')
    # ### end Alembic commands ###
